version: "3.7"

x-environment: &default-environment
  POSTGRES_USER: vscode
  POSTGRES_PASSWORD: password
  POSTGRES_DB: tutorial
  PGADMIN_DEFAULT_EMAIL: nikola.rusakov@rusakov.cz
  PGADMIN_DEFAULT_PASSWORD: password
# PGDATA: /var/lib/postgresql/data
# PGADMIN_EMAIL: nikola.rusakov@rusakov.cz
# PGADMIN_PASSWORD: password
# PGADMIN_PORT: 5050
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      <<: *default-environment
      PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace
    user: vscode
    command: sleep infinity
  db:
    image: "postgres:latest"
    restart: unless-stopped
    environment: *default-environment
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment: *default-environment
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - 5050:80

volumes:
  pgdata:
  pgadmin:
